import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [quote, setQuote] = useState("Click on the button below to fetch a quote");
  const [author, setAuthor] = useState("Adarsh");

  const getQuote = async () => {
    const response = await fetch("http://quotable.io/random");
    const parsedResponse = await response.json();
    setQuote(prevValue => parsedResponse.content);
    setAuthor(prevValue => parsedResponse.author);
  }

  return (
    <>
      <Head>
        <title>Quotes App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" fill="currentColor" className="bi bi-quote" viewBox="0 0 16 16">
          <path d="M12 12a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1h-1.388c0-.351.021-.703.062-1.054.062-.372.166-.703.31-.992.145-.29.331-.517.559-.683.227-.186.516-.279.868-.279V3c-.579 0-1.085.124-1.52.372a3.322 3.322 0 0 0-1.085.992 4.92 4.92 0 0 0-.62 1.458A7.712 7.712 0 0 0 9 7.558V11a1 1 0 0 0 1 1h2Zm-6 0a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1H4.612c0-.351.021-.703.062-1.054.062-.372.166-.703.31-.992.145-.29.331-.517.559-.683.227-.186.516-.279.868-.279V3c-.579 0-1.085.124-1.52.372a3.322 3.322 0 0 0-1.085.992 4.92 4.92 0 0 0-.62 1.458A7.712 7.712 0 0 0 3 7.558V11a1 1 0 0 0 1 1h2Z" />
        </svg>
        <h1>"{quote}"</h1>
        <h2>{author}</h2>
        <button onClick={getQuote}>Get Quote</button>
      </main>
    </>
  )
}
